# Generated by Django 5.2.17 on 2026-10-05 23:34

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nomor_bukti', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Nomor Kuitansi')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Kunci idempotensi untuk menjamin tidak ada duplikasi transaksi', max_length=64, unique=True, verbose_name='Idempotency Key')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Bayar (Rp)')),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai / Kasir'), ('transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('va', 'Virtual Account')], default='tunai', max_length=20, verbose_name='Metode Pembayaran')),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pembayaran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Transaksi')),
            ],
            options={
                'verbose_name': 'Transaksi Pembayaran',
                'verbose_name_plural': 'Daftar Transaksi Pembayaran',
                'ordering': ['-tanggal_bayar'],
            },
        ),
        migrations.CreateModel(
            name='PosTarif',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Pos')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Pos Pembayaran')),
                ('tipe', models.CharField(choices=[('rutin', 'Rutin (Bulanan)'), ('non_rutin', 'Non-Rutin (Bebas / Sekali Bayar)')], default='rutin', max_length=15, verbose_name='Tipe Tagihan')),
                ('tarif_standar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tarif Standar (Rp)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Pos Tarif',
                'verbose_name_plural': 'Daftar Pos Tarif',
                'ordering': ['tipe', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nomor_invoice', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Nomor Invoice')),
                ('bulan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bulan Tagihan')),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun Kalender')),
                ('nominal_awal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Asli (Rp)')),
                ('diskon', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Potongan / Beasiswa (Rp)')),
                ('total_tagihan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Wajib Bayar (Rp)')),
                ('total_terbayar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Terbayar (Rp)')),
                ('sisa_tagihan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sisa Tagihan (Rp)')),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('sebagian', 'Sebagian / Dicicil'), ('lunas', 'Lunas'), ('batal', 'Dibatalkan')], db_index=True, default='belum_bayar', max_length=20, verbose_name='Status Tagihan')),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan Tagihan')),
            ],
            options={
                'verbose_name': 'Tagihan Santri',
                'verbose_name_plural': 'Daftar Tagihan Santri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarifKhususSantri',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nominal_tarif', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Khusus (Rp)')),
                ('keterangan', models.CharField(blank=True, max_length=200, verbose_name='Alasan / Jenis Beasiswa')),
            ],
            options={
                'verbose_name': 'Tarif Khusus Santri',
                'verbose_name_plural': 'Daftar Tarif Khusus Santri',
            },
        ),
    ]
