# Generated by Django 5.2.17 on 2026-10-05 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keuangan', '0001_initial'),
        ('santri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_diterima', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Kasir'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pembayaran', to='santri.santri', verbose_name='Santri'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='pos_tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagihan_pos_list', to='keuangan.postarif', verbose_name='Pos Pembayaran'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagihan_list', to='santri.santri', verbose_name='Santri'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santri.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='tagihan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_list', to='keuangan.tagihan', verbose_name='Tagihan Terkait'),
        ),
        migrations.AddField(
            model_name='tarifkhusussantri',
            name='pos_tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarif_khusus_santri', to='keuangan.postarif', verbose_name='Pos Tarif'),
        ),
        migrations.AddField(
            model_name='tarifkhusussantri',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_khusus_list', to='santri.santri', verbose_name='Santri'),
        ),
        migrations.AddField(
            model_name='tarifkhusussantri',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santri.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AddConstraint(
            model_name='tagihan',
            constraint=models.CheckConstraint(condition=models.Q(('sisa_tagihan__gte', 0)), name='sisa_tagihan_tidak_boleh_negatif'),
        ),
        migrations.AddConstraint(
            model_name='tagihan',
            constraint=models.UniqueConstraint(condition=models.Q(('bulan__isnull', False), ('tahun__isnull', False)), fields=('santri', 'pos_tarif', 'bulan', 'tahun'), name='unique_tagihan_rutin_santri'),
        ),
        migrations.AddConstraint(
            model_name='tarifkhusussantri',
            constraint=models.UniqueConstraint(fields=('santri', 'pos_tarif', 'tahun_ajaran'), name='unique_tarif_khusus_santri_per_pos'),
        ),
    ]
