# Generated by Django 5.2.17 on 2026-10-05 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaRombel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('naik_kelas', 'Naik Kelas'), ('tinggal_kelas', 'Tinggal Kelas'), ('lulus', 'Lulus'), ('pindah', 'Pindah Rombel')], default='aktif', max_length=20, verbose_name='Status Keanggotaan')),
                ('catatan', models.CharField(blank=True, max_length=255, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Anggota Rombel',
                'verbose_name_plural': 'Daftar Anggota Rombel',
                'ordering': ['rombel', 'santri__nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Rombel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Rombel')),
                ('tingkat', models.PositiveSmallIntegerField(default=1, verbose_name='Tingkat / Kelas')),
                ('kapasitas', models.PositiveSmallIntegerField(default=30, verbose_name='Kapasitas Maksimal')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Rombongan Belajar',
                'verbose_name_plural': 'Daftar Rombongan Belajar',
                'ordering': ['tingkat', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nis', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nomor Induk Santri (NIS)')),
                ('nisn', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='NISN')),
                ('nik', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIK')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('panggilan', models.CharField(blank=True, max_length=50, verbose_name='Nama Panggilan')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat Asal')),
                ('nama_ayah', models.CharField(blank=True, max_length=100, verbose_name='Nama Ayah')),
                ('nama_ibu', models.CharField(blank=True, max_length=100, verbose_name='Nama Ibu')),
                ('nama_wali', models.CharField(blank=True, max_length=100, verbose_name='Nama Wali')),
                ('telepon_wali', models.CharField(blank=True, max_length=25, verbose_name='No. HP / WhatsApp Wali')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('mutasi', 'Mutasi / Pindah'), ('keluar', 'Keluar / DO'), ('alumni', 'Alumni')], default='aktif', max_length=15, verbose_name='Status Santri')),
                ('tanggal_masuk', models.DateField(blank=True, null=True, verbose_name='Tanggal Masuk')),
                ('tanggal_lulus', models.DateField(blank=True, null=True, verbose_name='Tanggal Kelulusan')),
                ('no_ijazah', models.CharField(blank=True, max_length=60, null=True, verbose_name='No. Ijazah / Syahadah')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='santri/foto/', verbose_name='Foto Santri')),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Daftar Santri',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('jenis', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10, verbose_name='Semester')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status Aktif')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Daftar Semester',
                'ordering': ['-tahun_ajaran__tanggal_mulai', 'jenis'],
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nama', models.CharField(max_length=20, unique=True, verbose_name='Tahun Ajaran')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status Aktif')),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Daftar Tahun Ajaran',
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
