# Generated by Django 5.2.17 on 2026-10-05 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('santri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rombel',
            name='wali_rombel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rombel_diampu', to=settings.AUTH_USER_MODEL, verbose_name='Wali Rombel / Wali Kelas'),
        ),
        migrations.AddField(
            model_name='anggotarombel',
            name='rombel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anggota_list', to='santri.rombel', verbose_name='Rombel'),
        ),
        migrations.AddField(
            model_name='santri',
            name='wali_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anak_santri', to=settings.AUTH_USER_MODEL, verbose_name='Akun User Wali Santri'),
        ),
        migrations.AddField(
            model_name='anggotarombel',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_rombel', to='santri.santri', verbose_name='Santri'),
        ),
        migrations.AddField(
            model_name='semester',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_list', to='santri.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AddField(
            model_name='rombel',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rombel_list', to='santri.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AddField(
            model_name='anggotarombel',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_anggota_rombel', to='santri.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('tahun_ajaran', 'jenis'), name='unique_semester_per_tahun'),
        ),
        migrations.AddConstraint(
            model_name='rombel',
            constraint=models.UniqueConstraint(fields=('nama', 'tahun_ajaran'), name='unique_rombel_per_tahun_ajaran'),
        ),
        migrations.AddConstraint(
            model_name='anggotarombel',
            constraint=models.UniqueConstraint(fields=('santri', 'tahun_ajaran'), name='unique_santri_per_tahun_ajaran'),
        ),
    ]
