# Generated by Django 5.2.17 on 2026-10-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='alamat_ayah',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_ayah_sama',
            field=models.BooleanField(default=True, verbose_name='Alamat Ayah Sama dengan Santri'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_ibu',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_ibu_sama',
            field=models.BooleanField(default=True, verbose_name='Alamat Ibu Sama dengan Santri'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_wali',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_wali_sama',
            field=models.BooleanField(default=True, verbose_name='Alamat Wali Sama dengan Santri'),
        ),
        migrations.AddField(
            model_name='santri',
            name='anak_ke',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Anak ke-'),
        ),
        migrations.AddField(
            model_name='santri',
            name='desa_kelurahan_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desa / Kelurahan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='desa_kelurahan_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desa / Kelurahan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='desa_kelurahan_santri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desa / Kelurahan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='desa_kelurahan_wali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desa / Kelurahan Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='golongan_darah',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('-', 'Tidak Tahu')], default='-', max_length=5, verbose_name='Golongan Darah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='hubungan_wali',
            field=models.CharField(choices=[('sama_ayah', 'Sama dengan Ayah Kandung'), ('sama_ibu', 'Sama dengan Ibu Kandung'), ('kakek_nenek', 'Kakek / Nenek'), ('paman_bibi', 'Paman / Bibi'), ('saudara', 'Kakak Kandung / Saudara'), ('lainnya', 'Wali Lainnya')], default='sama_ayah', max_length=25, verbose_name='Hubungan Wali dengan Santri'),
        ),
        migrations.AddField(
            model_name='santri',
            name='jumlah_saudara',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Dari Jumlah Saudara'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kabupaten_kota_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten / Kota Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kabupaten_kota_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten / Kota Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kabupaten_kota_santri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten / Kota'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kabupaten_kota_wali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten / Kota Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kecamatan_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kecamatan_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kecamatan_santri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kecamatan_wali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kode_pos_ayah',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kode_pos_ibu',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kode_pos_santri',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kode_pos_wali',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='nik_ayah',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIK Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='nik_ibu',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIK Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='nik_wali',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIK Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='no_kk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Kartu Keluarga (KK)'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pekerjaan_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pekerjaan_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pekerjaan_wali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pendidikan Terakhir Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pendidikan Terakhir Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='penghasilan_ayah',
            field=models.CharField(blank=True, max_length=50, verbose_name='Penghasilan Bulanan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='penghasilan_ibu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Penghasilan Bulanan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='penghasilan_wali',
            field=models.CharField(blank=True, max_length=50, verbose_name='Penghasilan Bulanan Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='provinsi_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='provinsi_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='provinsi_santri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='provinsi_wali',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi Wali'),
        ),
        migrations.AddField(
            model_name='santri',
            name='riwayat_penyakit',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit / Alergi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_ayah',
            field=models.CharField(choices=[('hidup', 'Masih Hidup'), ('meninggal', 'Meninggal Dunia (Alm/Almh)')], default='hidup', max_length=15, verbose_name='Status Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_ibu',
            field=models.CharField(choices=[('hidup', 'Masih Hidup'), ('meninggal', 'Meninggal Dunia (Alm/Almh)')], default='hidup', max_length=15, verbose_name='Status Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='telepon_ayah',
            field=models.CharField(blank=True, max_length=25, verbose_name='No. HP / WA Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='telepon_ibu',
            field=models.CharField(blank=True, max_length=25, verbose_name='No. HP / WA Ibu'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='alamat',
            field=models.TextField(blank=True, verbose_name='Alamat / Jalan / RT / RW'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIK Santri'),
        ),
    ]
